services:
  erp-integration:
    image: erp-integration
    restart: always
    ports:
      - "8083:8080"
    networks:
      - karavan
    environment:
       ERP_USER:{{env:ERP_USER}}
       ERP_PASSWORD:{{env:ERP_PASSWORD}}
